### PR TITLE
Make changes to only run PR when target branch is main or release-0.3

### PR DESCRIPTION
**Pull request by msajidmansoori12**

### CODE REVIEW

**Comment by aufi** [comment]
@msajidmansoori12 @mguetta1 I'm not sure if there is relevant reason for keep testing `release-0.3` when there are several newer releases including latest (not-yet released branch) 0.6, just created https://github.com/konveyor/go-konveyor-tests/issues/217 that might be refrected also in jenkins. Let's discuss relevant releases for testing there, thanks!

**Review by mguetta1 — COMMENTED** [review]
@msajidmansoori12 Could you please enable the PR tester only for `main` branch?

**Comment by msajidmansoori12** [comment]
@mguetta1 made the changes to only run for main branch , please merge.

**Review by mguetta1 — APPROVED** [review]
LGTM

**Pull request merged**
