### PR TITLE
Modify PR tester pipeline to only PRs with target branch as main and …

### PR DESCRIPTION
**Pull request by msajidmansoori12**
Modify PR tester pipeline to only run PRs with target branch as main and release-0.3 branch

### CODE REVIEW

**Comment by aufi** [comment]
I'm not sure about `release-0.3` release jenkins  testing, let's discuss it https://github.com/konveyor/go-konveyor-tests/issues/217

**Review by mguetta1 — COMMENTED** [review]
Hi @msajidmansoori12 
Could you please enable the PR tester only for `main` branch?

**Comment by msajidmansoori12** [comment]
@mguetta1 ack.

**Comment by msajidmansoori12** [comment]
@mguetta1 @aufi hello, i've made the changes to only run the pipeline for main branch , please merge. Thanks.

**Review by mguetta1 — APPROVED** [review]
LGTM

**Pull request merged**
