### PR TITLE
Ginkgo test: Unlink application from Jira

### PR DESCRIPTION
**Pull request by mguetta1**
Test setup:
- Create app, Jira connection and migration wave.
- Export app to Jira instance.

Test steps:

1. Delete Jira instance --> should fail because there is an issue associated with an application
2.  Delete ticket --> ticket successfully deleted and Jira instance can be removed

The test fails on the first step due to https://issues.redhat.com/browse/MTA-2226

Related to #14

### CODE REVIEW

**Review by sshveta — APPROVED** [review]

**Comment by sshveta** [comment]
According to comment on bug 2226 , JIRA instances can be deleted even if issues exists . First test should pass now.

**Comment by mguetta1** [comment]
> According to comment on bug 2226 , JIRA instances can be deleted even if issues exists . First test should pass now.

In that case, there is no reason to merge this PR
Ticket CRUD test is already coverd in tackle2-hub repo:
https://github.com/konveyor/tackle2-hub/blob/main/test/api/ticket/api_test.go

cc: @aufi

**Comment by aufi** [comment]
> In that case, there is no reason to merge this test Ticket CRUD test is already coverd in tackle2-hub repo: https://github.com/konveyor/tackle2-hub/blob/main/test/api/ticket/api_test.go
> 
> cc: @aufi

**Review by aufi — APPROVED** [review]
I don't see an overlapping with basic crud test in hub API as a problem, LGTM.

**Pull request merged**
