### PR TITLE
Upload binary analysis test

### PR DESCRIPTION
**Pull request by mguetta1**
Adding upload binary analysis test

* Please note that in order to get the Task ID and use it to upload the binary file, the Task resource is created with `State: "Created"`, and once the binary file is uploaded, the task is submitted by updating it with `State: "Ready"` 

* Skipping Incidents check due to the amount

### CODE REVIEW

**Review by aufi — APPROVED** [review]
Looks good to me, nice solution with Created/Ready task for artifact upload.

Just thinking about adding `AdministracionEfectivo.ear` file to this repo, do we know it is an open-source example?

**Comment by sshveta** [comment]
> AdministracionEfectivo.ear

This file was provided to us by MTR team (phil) for testing . 
We have been using it since then .
Let me check witht them on open source thing .

**Comment by sshveta** [comment]
> AdministracionEfectivo.ear

Not sure about this @mguetta1 . We can use [acmeair-webapp-1.0-SNAPSHOT.war](https://github.com/konveyor/tackle-ui-tests/blob/main/cypress/fixtures/acmeair-webapp-1.0-SNAPSHOT.war)  which we are using in tackle tests . Not sure about that one too though.

**Comment by mguetta1** [comment]
@sshveta @aufi I noticed that the file is already in a public repository:
https://github.com/konveyor/tackle-ui-tests/blob/main/cypress/fixtures/administracionEfectivo.ear

I added a function to download it

**Comment by aufi** [comment]
@pranavgaikwad for visibility

**Pull request merged**
